dist: trusty
language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'

# Optimize the build since we are `composer installing` for each supported
# Laravel versions (see composer.json, under scripts sections).
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  # Installing `Laravel-JS-Localization` package dependencies. If the current
  # PHP version is 5.5 then we should require minimum supported illuminate
  # dependencies.
  - if [[ `php -v` =~ "PHP 5.5" ]]; then composer require "illuminate/config:4.2.*" "illuminate/console:4.2.*" "illuminate/filesystem:4.2.*"; fi
  - composer install --prefer-dist --no-interaction
  # Installing `Laravel-JS-Localization` package dependencies for each
  # supported Laravel versions (see composer.json, under scripts section).
  - composer test-install

script: composer test
